board: fixup mount data script
Signed-off-by: Jean-Michel Hautbois <jeanmichel.hautbois@yoseli.org>

diff --git a/board/wabtec/common/rootfs_overlay/etc/init.d/S01mountdata b/board/wabtec/common/rootfs_overlay/etc/init.d/S01mountdata
--- a/board/wabtec/common/rootfs_overlay/etc/init.d/S01mountdata
+++ b/board/wabtec/common/rootfs_overlay/etc/init.d/S01mountdata
@@ -5,6 +5,50 @@ echo "Entering $0"
 # Define partitions and other variables (if needed, extend FOLDERS for multiple partitions)
 FOLDERS="/data"
 
+# Format and mount the UBI volume for mtd passed as argument
+format_data_partition() {
+	MTD_PART=$1
+	# Format the MTD partition for UBI
+	ubiformat /dev/${MTD_PART} -y -q
+
+	if [ $? -ne 0 ]; then
+	    echo "Error: ubiformat failed!" >&2
+	    exit 1
+	else
+	    echo "ubiformat succeeded"
+	fi
+
+	# Create a UBI volume
+	ubiattach /dev/ubi_ctrl -m ${MTD_PART#mtd}
+
+	if [ $? -ne 0 ]; then
+	    echo "Error: ubiattach failed!" >&2
+	    exit 1
+	else
+	    echo "ubiattach succeeded"
+	fi
+
+	# Format the UBIFS filesystem
+	ubimkvol /dev/ubi0 -N data -s 128MiB
+
+	if [ $? -ne 0 ]; then
+	    echo "Error: ubimkvol failed!" >&2
+	    exit 1
+	else
+	    echo "ubimkvol succeeded"
+	fi
+
+	# Mount the UBIFS filesystem
+	mkfs.ubifs -r /data -e 0x1f000 -c 2048 -m 0x800 /dev/ubi0_0
+
+	if [ $? -ne 0 ]; then
+	    echo "Error: Failed to create UBIFS filesystem!" >&2
+	    exit 1
+	else
+	    echo "/data mounted successfully"
+	fi
+}
+
 # Function to attach, format, and mount UBI volume
 mount_data_partition() {
 	# Find the MTD partition for "data"
@@ -15,27 +59,23 @@ mount_data_partition() {
 		exit 1
 	fi
 
+	# Check if the partition is UBI formatted
+	# nanddump -n -q -l 5 /dev/mtd6 |xxd                                                                                                                                                                                                
+	# 00000000: 5542 4923 01                             UBI#.
+
+	header=$(nanddump -n -q -l 3 /dev/${MTD_PART} | xxd | awk '{print $4}')
+	if [ "$header" = "UBI" ]; then
+		echo "UBI header found on /dev/${MTD_PART}"
+	else
+		echo "Error: UBI header not found on /dev/${MTD_PART}" >&2
+		format_data_partition ${MTD_PART}
+		exit 1
+	fi
+
 	# Attempt to attach the UBI volume
 	if ! ubiattach /dev/ubi_ctrl -m ${MTD_PART#mtd}; then
 		echo "ubiattach failed, attempting to format the partition"
-
-		# Format the MTD partition
-		if ! ubiformat /dev/${MTD_PART} -y; then
-		    echo "Error: Failed to format the MTD partition!" >&2
-		    exit 1
-		fi
-
-		# Create a new UBI volume
-		if ! ubimkvol /dev/ubi0 -N data -s 128MiB; then
-		    echo "Error: Failed to create UBI volume!" >&2
-		    exit 1
-		fi
-
-		# Create the UBIFS filesystem
-		if ! mkfs.ubifs -r /data -e 0x1f000 -c 2048 -m 0x800 /dev/ubi0_0; then
-		    echo "Error: Failed to create UBIFS filesystem!" >&2
-		    exit 1
-		fi
+		format_data_partition ${MTD_PART}
 	else
 		echo "UBI volume attached successfully"
 	fi
